platform :ios, '13.0'

inhibit_all_warnings!

target 'ConPresApp' do
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  pod 'SideMenu'
  pod 'SwiftDate', '~> 5.0'
  pod 'Moya', '~> 14.0'
end
