platform :ios, '13.0'

inhibit_all_warnings!

target 'ConPresApp' do
  use_frameworks!
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  pod 'SideMenuSwift'
end
